<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="story" nsURI="urn:org.nasdanika.story" nsPrefix="org.nasdanika.story">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Story model allows to capture agile (user) stories in the form of a model which can reference the domain model and be linked to the domain model, e.g. route operations may reference user stories they are used by. The story model can be used for documentation, to link test results to acceptance criteria (also as part of online documentation), and for story-based entitlements - operations reference stories, and users are granted entitlements execute stories, or users are granted roles, which in turn are linked to stories."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Catalog" eSuperTypes="#//CatalogElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for catalog elements - [[Story|Stories]], [[Actor|Actors]], [[Role|Roles]], [[Epic|Epics]], [[Theme|Themes]], ..."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//CatalogElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatalogElement" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for model elements which can be added to a catalog."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unique, in the containing resource, catalog element identifier. Identifiers are automatically generated when an element is added to a catalog."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element name."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element description. Supports markup. Some catalog elements may hide description attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Protagonist" abstract="true" eSuperTypes="#//StoryContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface representing the main character of a story."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkTo" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoryBase" abstract="true" eSuperTypes="#//CatalogElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="protagonists" lowerBound="1"
        upperBound="-1" eType="#//Protagonist">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A story shall have at least one protagonist. If a story is played by multiple types of protagonists, more than one protagonist can be set for the story to obviate artificial generalization relationships between protagonists."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="themes" upperBound="-1"
        eType="#//Theme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//Protagonist">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subRoles" upperBound="-1"
        eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superRoles" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true" eSuperTypes="#//Protagonist">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base interface for actors."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Actor can play zero or more roles."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subActors" upperBound="-1"
        eType="#//Actor" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sub-actors may be contained by the super-actor to form a single-inheritance hierarchy. Multiple inheritance can be set up with superActors reference."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superActors" upperBound="-1"
        eType="#//Actor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Actors form a multiple inheritance hierarcy and may have zero or more super-actors. All stories and roles played by by a super-actor are also played by its sub-actors."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Persona" eSuperTypes="#//User"/>
  <eClassifiers xsi:type="ecore:EClass" name="Epic" eSuperTypes="#//StoryContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Story" eSuperTypes="#//StoryBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="acceptancecriteria" upperBound="-1"
        eType="#//AcceptanceCriterion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depends" upperBound="-1"
        eType="#//Story"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Theme" eSuperTypes="#//CatalogElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Theme" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcceptanceCriterion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalProtagonist">
    <eStructuralFeatures xsi:type="ecore:EReference" name="protagonist" lowerBound="1"
        upperBound="-1" eType="#//Protagonist"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoryContainer" abstract="true" eSuperTypes="#//CatalogElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stories" upperBound="-1"
        eType="#//StoryBase" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
