<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="flow" nsURI="urn:org.nasdanika.cdo.flow" nsPrefix="org.nasdanika.cdo.flow">
  <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target">
      <eGenericType eTypeParameter="#//Reference/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Then" abstract="true" interface="true">
    <eTypeParameters name="R"/>
    <eTypeParameters name="R1"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="onFulfilled" eExceptions="#//Exception">
      <eGenericType eTypeParameter="#//Then/R1"/>
      <eParameters name="value">
        <eGenericType eTypeParameter="#//Then/R"/>
      </eParameters>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Then/C"/>
      </eParameters>
    </eOperations>
    <eOperations name="onRejected" eType="#//Exception" eExceptions="#//Exception">
      <eParameters name="reason" eType="#//Exception"/>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Then/C"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThenReference">
    <eTypeParameters name="R"/>
    <eTypeParameters name="R1"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Reference">
      <eTypeArguments eClassifier="#//Then">
        <eTypeArguments eTypeParameter="#//ThenReference/R"/>
        <eTypeArguments eTypeParameter="#//ThenReference/R1"/>
        <eTypeArguments eTypeParameter="#//ThenReference/C"/>
      </eTypeArguments>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Then">
      <eTypeArguments eTypeParameter="#//ThenReference/R"/>
      <eTypeArguments eTypeParameter="#//ThenReference/R1"/>
      <eTypeArguments eTypeParameter="#//ThenReference/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PromiseState">
    <eLiterals name="PENDING"/>
    <eLiterals name="FULFILLED" value="1"/>
    <eLiterals name="REJECTED" value="2"/>
    <eLiterals name="CANCELLED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executor" instanceClassName="org.nasdanika.cdo.flow.Executor"
      abstract="true" interface="true">
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Promise" abstract="true" interface="true">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="then">
      <eGenericType eClassifier="#//Promise">
        <eTypeArguments eTypeParameter="#//Promise/then/R1"/>
        <eTypeArguments eTypeParameter="#//Promise/C"/>
      </eGenericType>
      <eTypeParameters name="R1"/>
      <eParameters name="then">
        <eGenericType eClassifier="#//Then">
          <eTypeArguments eTypeParameter="#//Promise/R"/>
          <eTypeArguments eTypeParameter="#//Promise/then/R1"/>
          <eTypeArguments eTypeParameter="#//Promise/C"/>
        </eGenericType>
      </eParameters>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Promise/C"/>
      </eParameters>
      <eParameters name="executor">
        <eGenericType eClassifier="#//Executor">
          <eTypeArguments eTypeParameter="#//Promise/C"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getFulfillmentValue">
      <eGenericType eTypeParameter="#//Promise/R"/>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Promise/C"/>
      </eParameters>
    </eOperations>
    <eOperations name="getRejectionReason" eType="#//Exception">
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Promise/C"/>
      </eParameters>
    </eOperations>
    <eOperations name="getState" eType="#//PromiseState"/>
    <eOperations name="cancel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="done" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expires" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PromiseReference">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Promise">
      <eTypeArguments eTypeParameter="#//PromiseReference/R"/>
      <eTypeArguments eTypeParameter="#//PromiseReference/C"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Reference">
      <eTypeArguments eClassifier="#//Promise">
        <eTypeArguments eTypeParameter="#//PromiseReference/R"/>
        <eTypeArguments eTypeParameter="#//PromiseReference/C"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="All">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="init">
      <eParameters name="promises" upperBound="-1">
        <eGenericType eClassifier="#//Promise">
          <eTypeArguments/>
          <eTypeArguments eTypeParameter="#//All/C"/>
        </eGenericType>
      </eParameters>
      <eParameters name="executor">
        <eGenericType eClassifier="#//Executor">
          <eTypeArguments eTypeParameter="#//All/C"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//Promise">
      <eTypeArguments eTypeParameter="#//All/R"/>
      <eTypeArguments eTypeParameter="#//All/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Any">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="init">
      <eParameters name="promises" upperBound="-1">
        <eGenericType eClassifier="#//Promise">
          <eTypeArguments eTypeParameter="#//Any/R"/>
          <eTypeArguments eTypeParameter="#//Any/C"/>
        </eGenericType>
      </eParameters>
      <eParameters name="executor">
        <eGenericType eClassifier="#//Executor">
          <eTypeArguments eTypeParameter="#//Any/C"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//Promise">
      <eTypeArguments eTypeParameter="#//Any/R"/>
      <eTypeArguments eTypeParameter="#//Any/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" interface="true">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="execute" eExceptions="#//Exception">
      <eGenericType eTypeParameter="#//Command/R"/>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Command/C"/>
      </eParameters>
      <eParameters name="executor">
        <eGenericType eClassifier="#//Executor">
          <eTypeArguments eTypeParameter="#//Command/C"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deferred">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="resolve">
      <eParameters name="value">
        <eGenericType eTypeParameter="#//Deferred/R"/>
      </eParameters>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Deferred/C"/>
      </eParameters>
      <eParameters name="executor">
        <eGenericType eClassifier="#//Executor">
          <eTypeArguments eTypeParameter="#//Deferred/C"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="resolve">
      <eParameters name="promise">
        <eGenericType eClassifier="#//Promise">
          <eTypeArguments eTypeParameter="#//Deferred/R"/>
          <eTypeArguments eTypeParameter="#//Deferred/C"/>
        </eGenericType>
      </eParameters>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Deferred/C"/>
      </eParameters>
      <eParameters name="executor">
        <eGenericType eClassifier="#//Executor">
          <eTypeArguments eTypeParameter="#//Deferred/C"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="reject">
      <eParameters name="reason" eType="#//Exception"/>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Deferred/C"/>
      </eParameters>
      <eParameters name="executor">
        <eGenericType eClassifier="#//Executor">
          <eTypeArguments eTypeParameter="#//Deferred/C"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//PromiseState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolved" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolution" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" containment="true">
      <eGenericType eClassifier="#//Then">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eTypeArguments eTypeParameter="#//Deferred/R"/>
        <eTypeArguments eTypeParameter="#//Deferred/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenDeferreds" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//Deferred">
        <eTypeArguments/>
        <eTypeArguments eTypeParameter="#//Deferred/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Promise">
      <eTypeArguments eTypeParameter="#//Deferred/R"/>
      <eTypeArguments eTypeParameter="#//Deferred/C"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Command">
      <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eTypeArguments eTypeParameter="#//Deferred/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="canExecute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command">
      <eGenericType eClassifier="#//Command">
        <eTypeArguments eTypeParameter="#//Job/R"/>
        <eTypeArguments eTypeParameter="#//Job/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deferred">
      <eGenericType eClassifier="#//Deferred">
        <eTypeArguments eTypeParameter="#//Job/R"/>
        <eTypeArguments eTypeParameter="#//Job/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="started" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//JobStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JobStatus">
    <eLiterals name="PENDING"/>
    <eLiterals name="RUNNING" value="1"/>
    <eLiterals name="COMPLETED" value="2"/>
    <eLiterals name="FAILED" value="3"/>
    <eLiterals name="ROLLEDBACK" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobQueue" abstract="true" interface="true">
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" upperBound="-1" containment="true">
      <eGenericType eClassifier="#//Job">
        <eTypeArguments/>
        <eTypeArguments eTypeParameter="#//JobQueue/C"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionState">
    <eLiterals name="PASSIVE"/>
    <eLiterals name="ACTIVATING" value="1"/>
    <eLiterals name="ACTIVE" value="2"/>
    <eLiterals name="PASSIVATING" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Context" instanceClassName="org.nasdanika.core.Context"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" abstract="true" interface="true">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorReference" abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eTypeParameters name="A">
      <eBounds eClassifier="#//Actuator">
        <eTypeArguments eTypeParameter="#//ActuatorReference/T"/>
      </eBounds>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Actuator">
      <eTypeArguments eTypeParameter="#//ActuatorReference/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Reference">
      <eTypeArguments eTypeParameter="#//ActuatorReference/A"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invocable" abstract="true" interface="true">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="invoke" eExceptions="#//Exception">
      <eGenericType eTypeParameter="#//Invocable/R"/>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Invocable/C"/>
      </eParameters>
      <eParameters name="arguments" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="accept" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        eExceptions="#//Exception">
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Invocable/C"/>
      </eParameters>
      <eParameters name="arguments" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//Actuator">
      <eTypeArguments eTypeParameter="#//Invocable/R"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocableThen">
    <eTypeParameters name="R"/>
    <eTypeParameters name="R1"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onFulfilled" containment="true">
      <eGenericType eClassifier="#//Invocable">
        <eTypeArguments eTypeParameter="#//InvocableThen/R1"/>
        <eTypeArguments eTypeParameter="#//InvocableThen/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onRejected" containment="true">
      <eGenericType eClassifier="#//Invocable">
        <eTypeArguments eClassifier="#//Exception"/>
        <eTypeArguments eTypeParameter="#//InvocableThen/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Then">
      <eTypeArguments eTypeParameter="#//InvocableThen/R"/>
      <eTypeArguments eTypeParameter="#//InvocableThen/R1"/>
      <eTypeArguments eTypeParameter="#//InvocableThen/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocableReference">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Invocable">
      <eTypeArguments eTypeParameter="#//InvocableReference/R"/>
      <eTypeArguments eTypeParameter="#//InvocableReference/C"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//ActuatorReference">
      <eTypeArguments eTypeParameter="#//InvocableReference/R"/>
      <eTypeArguments eClassifier="#//Invocable">
        <eTypeArguments eTypeParameter="#//InvocableReference/R"/>
        <eTypeArguments eTypeParameter="#//InvocableReference/C"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundInvocable">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="bind" eExceptions="#//Exception">
      <eParameters name="context">
        <eGenericType eTypeParameter="#//BoundInvocable/C"/>
      </eParameters>
      <eParameters name="arguments" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" containment="true">
      <eGenericType eClassifier="#//Invocable">
        <eTypeArguments eTypeParameter="#//BoundInvocable/R"/>
        <eTypeArguments eTypeParameter="#//BoundInvocable/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Invocable">
      <eTypeArguments eTypeParameter="#//BoundInvocable/R"/>
      <eTypeArguments eTypeParameter="#//BoundInvocable/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeferringInvocable">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" containment="true">
      <eGenericType eClassifier="#//Invocable">
        <eTypeArguments eTypeParameter="#//DeferringInvocable/R"/>
        <eTypeArguments eTypeParameter="#//DeferringInvocable/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" upperBound="-1">
      <eGenericType eClassifier="#//DeferredInvocation">
        <eTypeArguments eTypeParameter="#//DeferringInvocable/R"/>
        <eTypeArguments eTypeParameter="#//DeferringInvocable/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eGenericSuperTypes eClassifier="#//Invocable">
      <eTypeArguments eClassifier="#//Promise">
        <eTypeArguments eTypeParameter="#//DeferringInvocable/R"/>
        <eTypeArguments eTypeParameter="#//DeferringInvocable/C"/>
      </eTypeArguments>
      <eTypeArguments eTypeParameter="#//DeferringInvocable/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeferredInvocation">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" containment="true">
      <eGenericType eClassifier="#//Promise">
        <eTypeArguments eTypeParameter="#//DeferredInvocation/R"/>
        <eTypeArguments eTypeParameter="#//DeferredInvocation/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Command">
      <eTypeArguments eTypeParameter="#//DeferredInvocation/R"/>
      <eTypeArguments eTypeParameter="#//DeferredInvocation/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eOperations name="get">
      <eGenericType eTypeParameter="#//Property/T"/>
    </eOperations>
    <eOperations name="set">
      <eParameters name="value">
        <eGenericType eTypeParameter="#//Property/T"/>
      </eParameters>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//Actuator">
      <eTypeArguments eTypeParameter="#//Property/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyReference">
    <eTypeParameters name="T"/>
    <eGenericSuperTypes eClassifier="#//Property">
      <eTypeArguments eTypeParameter="#//PropertyReference/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//ActuatorReference">
      <eTypeArguments eTypeParameter="#//PropertyReference/T"/>
      <eTypeArguments eClassifier="#//Property">
        <eTypeArguments eTypeParameter="#//PropertyReference/T"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" interface="true">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//ActionOutputEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorHandlers" upperBound="-1"
        eType="#//ErrorHandlerEntry" containment="true"/>
    <eGenericSuperTypes eClassifier="#//Invocable">
      <eTypeArguments eTypeParameter="#//Action/R"/>
      <eTypeArguments eTypeParameter="#//Action/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaActionDelegate" instanceClassName="org.nasdanika.cdo.flow.JavaActionDelegate"
      abstract="true" interface="true">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaAction">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delegate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//PropertyEntry" containment="true"/>
    <eGenericSuperTypes eClassifier="#//Action">
      <eTypeArguments eTypeParameter="#//JavaAction/R"/>
      <eTypeArguments eTypeParameter="#//JavaAction/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionOutputEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true">
      <eGenericType eClassifier="#//Actuator">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorHandlerEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true">
      <eGenericType eClassifier="#//Invocable">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dispatch">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//Invocable">
        <eTypeArguments eTypeParameter="#//Dispatch/R"/>
        <eTypeArguments eTypeParameter="#//Dispatch/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Invocable">
      <eTypeArguments eTypeParameter="#//Dispatch/R"/>
      <eTypeArguments eTypeParameter="#//Dispatch/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EClass" name="Publish">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//Invocable">
        <eTypeArguments eTypeParameter="#//Publish/R"/>
        <eTypeArguments eTypeParameter="#//Publish/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Invocable">
      <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eTypeParameter="#//Publish/R"/>
      </eTypeArguments>
      <eTypeArguments eTypeParameter="#//Publish/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CDOTransactionContext" instanceClassName="org.nasdanika.cdo.CDOTransactionContext"/>
  <eClassifiers xsi:type="ecore:EClass" name="Adaptable" instanceClassName="org.nasdanika.core.Adaptable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flow">
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="adapt">
      <eGenericType eTypeParameter="#//Flow/adapt/T"/>
      <eTypeParameters name="T"/>
      <eParameters name="type">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//Flow/adapt/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="context">
        <eGenericType eTypeParameter="#//Flow/C"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//FlowInputEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//FlowOutputEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorHandler" containment="true">
      <eGenericType eClassifier="#//InvocableReference">
        <eTypeArguments/>
        <eTypeArguments eTypeParameter="#//Flow/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//JobQueue">
      <eTypeArguments eTypeParameter="#//Flow/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowInputEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true">
      <eGenericType eClassifier="#//Actuator">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowOutputEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true">
      <eGenericType eClassifier="#//ActuatorReference">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinElement">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collector" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eGenericSuperTypes eClassifier="#//DeferredInvocation">
      <eTypeArguments eTypeParameter="#//JoinElement/R"/>
      <eTypeArguments eTypeParameter="#//JoinElement/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinInput">
    <eTypeParameters name="R"/>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//JoinElement">
        <eTypeArguments eTypeParameter="#//JoinInput/R"/>
        <eTypeArguments eTypeParameter="#//JoinInput/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Invocable">
      <eTypeArguments eTypeParameter="#//JoinInput/R"/>
      <eTypeArguments eTypeParameter="#//JoinInput/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinInputEntry" instanceClassName="java.util.Map$Entry">
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value">
      <eGenericType eClassifier="#//JoinInput">
        <eTypeArguments/>
        <eTypeArguments eTypeParameter="#//JoinInputEntry/C"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join">
    <eTypeParameters name="C">
      <eBounds eClassifier="#//Context"/>
    </eTypeParameters>
    <eOperations name="finishJoin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs">
      <eGenericType eClassifier="#//JoinInputEntry">
        <eTypeArguments eTypeParameter="#//Join/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joiner" containment="true">
      <eGenericType eClassifier="#//Invocable">
        <eTypeArguments/>
        <eTypeArguments eTypeParameter="#//Join/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//JobQueue">
      <eTypeArguments eTypeParameter="#//Join/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueProperty">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eGenericSuperTypes eClassifier="#//Property">
      <eTypeArguments eTypeParameter="#//ValueProperty/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" instanceClassName="org.nasdanika.core.Component"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceReference">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//Property">
      <eTypeArguments eTypeParameter="#//ServiceReference/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Component"/>
  </eClassifiers>
</ecore:EPackage>
