<%@ jet package="org.nasdanika.workspace.wizard" class="DockerfileRenderer" skeleton="Renderer.skeleton" %>
FROM centos

RUN yum update -y \
	&& yum install -y \
		java-1.8.0-openjdk-devel \
		graphviz \
	&& yum clean all 
		

COPY x86_64 /opt/<%=wizard.getDashedName()%>

RUN chmod a+x /opt/<%=wizard.getDashedName()%>/eclipse	

ENTRYPOINT ["/opt/<%=wizard.getDashedName()%>/eclipse"]

EXPOSE 8080